baseURL = "https://blog.regonn.tokyo/"
languageCode = "ja-jp"
title = "そこのけそこのけゆとりが通る"
googleAnalytics = ""
theme = "amp-start-blog"

[permalinks]
posts = "/:slug/:filename/"
pages = "/:filename/"

[params]
author = "Regonn"
logo = "/img/avatar.png"
twitter = "regonn_haizine"
github = "regonn"
instagram = "regonn_haizin"
youtube = "UCg6N2lmVe6GE3CvShuv6bTg"
reddit = "regonn314"
pinterest = "regonn"
description = "データサイエンティストを目指してるフリーランスのWEBプログラマ"

[taxonomies]
tag = "tags"
category = "categories"

[blackfriday]
hrefTargetBlank = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
